
package Visual;

import java.awt.event.WindowAdapter;

import java.awt.event.WindowEvent;

import java.util.ArrayList;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import sistemaeducativo.Alumno;
import sistemaeducativo.Asignatura;
import sistemaeducativo.Facultad;
import sistemaeducativo.MailInvalidoException;
import sistemaeducativo.NoExisteEntidadException;

/**
 *
 * @author Usuario
 */
public class VentanaAlumno extends javax.swing.JFrame
    
{
    private Facultad facultad;
    private DefaultListModel modeloBaja;
    private DefaultListModel modeloConsulta;
    private DefaultListModel modeloMod;
    private DefaultListModel modeloConsultaAsig;
    
    private VentanaPrincipal ventana;
    
    /** Creates new form VentanaAlumno */
    public VentanaAlumno(Facultad facultad, VentanaPrincipal ventana)
    {
        initComponents();
        this.facultad=facultad;
        this.ventana=ventana;
        this.cerrar();
        this.disable();
        setResizable(false);
        setTitle("Sistema Educativo -Alumno");
        setLocationRelativeTo(null);
        this.modeloBaja=new DefaultListModel();
        this.modeloConsultaAsig=new DefaultListModel();
        this.modeloConsulta = new DefaultListModel();
        this.modeloMod = new DefaultListModel();

    }
    public void disable(){
        this.jTextFieldLegajoConsultaa.disable();
        this.jTextFieldApellidoConsultaa.disable();
        this.jTextFieldNombreConsultaa.disable();
        this.jTextFieldDomicilioConsulta.disable();
        this.jTextFieldMailConsulta.disable();
        this.jListAsignaturasAprobadasConsulta.disable();
    }
    public void limpiarModelo()
    {
        this.modeloConsulta.clear();
        this.modeloBaja.clear();
        this.modeloMod.clear();
        this.modeloConsultaAsig.clear();
    }
    public void limpiarTextFieldAlta()
    {
        this.jTextFieldApellidoAlta.setText("");
        this.jTextFieldNombreAlta.setText("");
        this.jTextFieldMailAlta.setText("");
        this.jTextFieldDomicilioAlta.setText("");
    }
    public boolean validarAlta()
    {
        if(this.jTextFieldApellidoAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldNombreAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldMailAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldDomicilioAlta.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    public boolean validarMod()
    {
        if(this.jTextFieldApellidoNuevoMod.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldNombreNuevoMod.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldMailNuevoMod.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldDomicilioNuevoMod.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelAltaAlumno = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonVolverAlta = new javax.swing.JButton();
        jButtonConfirmarAlta = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabelNombreAlta = new javax.swing.JLabel();
        jLabelApellidoAlta = new javax.swing.JLabel();
        jLabelDomicilioAlta = new javax.swing.JLabel();
        jLabelMailAlta = new javax.swing.JLabel();
        jTextFieldNombreAlta = new javax.swing.JTextField();
        jTextFieldApellidoAlta = new javax.swing.JTextField();
        jTextFieldDomicilioAlta = new javax.swing.JTextField();
        jTextFieldMailAlta = new javax.swing.JTextField();
        jPanelBajaAlumno = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlumnosBaja = new javax.swing.JList<>();
        jButtonVolverBaja = new javax.swing.JButton();
        jButtonEliminarBaja = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelApellidoBaja = new javax.swing.JLabel();
        jLabelNombreBaja = new javax.swing.JLabel();
        jTextFieldNombreBaja = new javax.swing.JTextField();
        jTextFieldApellidoBaja = new javax.swing.JTextField();
        jButtonBuscarBaja = new javax.swing.JButton();
        jPanelModAlumno = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNombreMod = new javax.swing.JLabel();
        jTextFieldNombreMod = new javax.swing.JTextField();
        jLabelApellidoMod = new javax.swing.JLabel();
        jTextFieldApellidoMod = new javax.swing.JTextField();
        jButtonBuscarMod = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlumnosMod = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabelNombreNuevoMod = new javax.swing.JLabel();
        jTextFieldNombreNuevoMod = new javax.swing.JTextField();
        jLabelApellidoNuevoMod = new javax.swing.JLabel();
        jTextFieldApellidoNuevoMod = new javax.swing.JTextField();
        jLabelMailNuevoMod = new javax.swing.JLabel();
        jTextFieldMailNuevoMod = new javax.swing.JTextField();
        jLabelDomicilioNuevoMod = new javax.swing.JLabel();
        jTextFieldDomicilioNuevoMod = new javax.swing.JTextField();
        jButtonConfirmarMod = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonAsigAprobMod = new javax.swing.JButton();
        jButtonVolverMod = new javax.swing.JButton();
        jPanelConsultaAlumno = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelNombreConsulta = new javax.swing.JLabel();
        jTextFieldNombreConsulta = new javax.swing.JTextField();
        jLabelApellidoConsulta = new javax.swing.JLabel();
        jTextFieldApellidoConsulta = new javax.swing.JTextField();
        jButtonBuscarConsulta = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAlumnosConsulta = new javax.swing.JList<>();
        jButtonCargarConsulta = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldLegajoConsultaa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldNombreConsultaa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldApellidoConsultaa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldDomicilioConsulta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldMailConsulta = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAsignaturasAprobadasConsulta = new javax.swing.JList<>();
        jPanel16 = new javax.swing.JPanel();
        jButtonVolverConsulta = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonVolverAlta.setText("Volver");
        jButtonVolverAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAltaActionPerformed(evt);
            }
        });

        jButtonConfirmarAlta.setText("Confirmar Alta");
        jButtonConfirmarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarAltaActionPerformed(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de alumno"));

        jLabelNombreAlta.setText("Nombre");

        jLabelApellidoAlta.setText("Apellido");

        jLabelDomicilioAlta.setText("Domicilio");

        jLabelMailAlta.setText("Mail");

        jTextFieldNombreAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAltaActionPerformed(evt);
            }
        });

        jTextFieldApellidoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoAltaActionPerformed(evt);
            }
        });

        jTextFieldDomicilioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDomicilioAltaActionPerformed(evt);
            }
        });

        jTextFieldMailAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreAlta)
                    .addComponent(jLabelApellidoAlta)
                    .addComponent(jLabelDomicilioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMailAlta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldMailAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jTextFieldDomicilioAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellidoAlta)
                    .addComponent(jTextFieldNombreAlta))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombreAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidoAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldApellidoAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDomicilioAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDomicilioAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMailAlta)
                    .addComponent(jTextFieldMailAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButtonConfirmarAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolverAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmarAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jButtonVolverAlta)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAltaAlumnoLayout = new javax.swing.GroupLayout(jPanelAltaAlumno);
        jPanelAltaAlumno.setLayout(jPanelAltaAlumnoLayout);
        jPanelAltaAlumnoLayout.setHorizontalGroup(
            jPanelAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAltaAlumnoLayout.setVerticalGroup(
            jPanelAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Alta", jPanelAltaAlumno);

        jPanelBajaAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el alumno a eliminar"));

        jScrollPane1.setViewportView(jListAlumnosBaja);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonVolverBaja.setText("Volver");
        jButtonVolverBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverBajaActionPerformed(evt);
            }
        });

        jButtonEliminarBaja.setText("Eliminar alumno ");
        jButtonEliminarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarBajaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de alumno"));

        jLabelApellidoBaja.setText("Apellido del alumno a dar de baja:");

        jLabelNombreBaja.setText("Nombre del alumno a dar de baja:");

        jButtonBuscarBaja.setText("Buscar");
        jButtonBuscarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombreBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jLabelApellidoBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBuscarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreBaja)
                    .addComponent(jTextFieldNombreBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoBaja)
                    .addComponent(jTextFieldApellidoBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarBaja)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanelBajaAlumnoLayout = new javax.swing.GroupLayout(jPanelBajaAlumno);
        jPanelBajaAlumno.setLayout(jPanelBajaAlumnoLayout);
        jPanelBajaAlumnoLayout.setHorizontalGroup(
            jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajaAlumnoLayout.createSequentialGroup()
                .addGroup(jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBajaAlumnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVolverBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBajaAlumnoLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButtonEliminarBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelBajaAlumnoLayout.setVerticalGroup(
            jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminarBaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jButtonVolverBaja)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Baja", jPanelBajaAlumno);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de alumno"));
        jPanel4.setToolTipText("");

        jLabelNombreMod.setText("Nombre del alumno:");

        jLabelApellidoMod.setText("Apellido del alumno:");

        jButtonBuscarMod.setText("Buscar");
        jButtonBuscarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellidoMod)
                    .addComponent(jLabelNombreMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jButtonBuscarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreMod)
                            .addComponent(jTextFieldNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoMod)
                            .addComponent(jTextFieldApellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonBuscarMod)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el alumno a modificar"));

        jScrollPane2.setViewportView(jListAlumnosMod);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos a modificar"));

        jLabelNombreNuevoMod.setText("Nombre nuevo");

        jLabelApellidoNuevoMod.setText("Apellido nuevo");

        jLabelMailNuevoMod.setText("Mail nuevo");

        jLabelDomicilioNuevoMod.setText("Domicilio nuevo");

        jButtonConfirmarMod.setText("Confirmar Cambios");
        jButtonConfirmarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarModActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Altas y bajas de asignaturas aprobadas"));
        jPanel1.setToolTipText("");

        jButtonAsigAprobMod.setText("Ir a modificacion de historia");
        jButtonAsigAprobMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsigAprobModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAsigAprobMod, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButtonAsigAprobMod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombreNuevoMod, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelApellidoNuevoMod, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelDomicilioNuevoMod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldMailNuevoMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreNuevoMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApellidoNuevoMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDomicilioNuevoMod)))
                    .addComponent(jLabelMailNuevoMod))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButtonConfirmarMod, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreNuevoMod)
                            .addComponent(jTextFieldNombreNuevoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoNuevoMod)
                            .addComponent(jTextFieldApellidoNuevoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMailNuevoMod)
                            .addComponent(jTextFieldMailNuevoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDomicilioNuevoMod)
                            .addComponent(jTextFieldDomicilioNuevoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmarMod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonVolverMod.setText("Volver");
        jButtonVolverMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModAlumnoLayout = new javax.swing.GroupLayout(jPanelModAlumno);
        jPanelModAlumno.setLayout(jPanelModAlumnoLayout);
        jPanelModAlumnoLayout.setHorizontalGroup(
            jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                        .addComponent(jButtonVolverMod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelModAlumnoLayout.setVerticalGroup(
            jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModAlumnoLayout.createSequentialGroup()
                .addGap(0, 137, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonVolverMod)
                .addContainerGap())
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(518, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Modificaciones", jPanelModAlumno);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de alumno"));

        jLabelNombreConsulta.setText("  Nombre del alumno ");

        jLabelApellidoConsulta.setText("  Apellido del alumno ");

        jButtonBuscarConsulta.setText("Buscar");
        jButtonBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelApellidoConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButtonBuscarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombreConsulta)
                            .addComponent(jTextFieldNombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoConsulta)
                            .addComponent(jTextFieldApellidoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBuscarConsulta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione el alumno a consultar"));

        jScrollPane3.setViewportView(jListAlumnosConsulta);

        jButtonCargarConsulta.setText("Cargar");
        jButtonCargarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonCargarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonCargarConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));
        jPanel13.setToolTipText("");

        jLabel19.setText("  Legajo");

        jTextFieldLegajoConsultaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLegajoConsultaaActionPerformed(evt);
            }
        });

        jLabel21.setText("  Nombre");

        jLabel20.setText("  Apellido");

        jLabel23.setText("  Domicilio");

        jLabel22.setText("  Mail");

        jTextFieldMailConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldLegajoConsultaa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreConsultaa)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellidoConsultaa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDomicilioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMailConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMailConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldDomicilioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLegajoConsultaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreConsultaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldApellidoConsultaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignaturas aprobadas"));

        jScrollPane4.setViewportView(jListAsignaturasAprobadasConsulta);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jButtonVolverConsulta.setText("Volver");
        jButtonVolverConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultaAlumnoLayout = new javax.swing.GroupLayout(jPanelConsultaAlumno);
        jPanelConsultaAlumno.setLayout(jPanelConsultaAlumnoLayout);
        jPanelConsultaAlumnoLayout.setHorizontalGroup(
            jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                        .addComponent(jButtonVolverConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelConsultaAlumnoLayout.setVerticalGroup(
            jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaAlumnoLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaAlumnoLayout.createSequentialGroup()
                        .addComponent(jButtonVolverConsulta)
                        .addContainerGap())))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Consulta", jPanelConsultaAlumno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldMailAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldMailAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldMailAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailAltaActionPerformed

    private void jButtonConfirmarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmarModActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmarModActionPerformed
        // TODO add your handling code here:
        int n=this.jListAlumnosMod.getSelectedIndex();
        if(n!=-1) {
            Alumno a=(Alumno) this.modeloMod.getElementAt(n);
            if(this.validarMod())
            {
                String mail= this.jTextFieldMailNuevoMod.getText();
                int valor=JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea modificar a "+a.getApellido()+"?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                if(valor==JOptionPane.YES_OPTION){
                    try {
                        facultad.modificarAlumno(a, this.jTextFieldApellidoNuevoMod
                                                        .getText()
                                                        .toUpperCase(), this.jTextFieldNombreNuevoMod
                                                                            .getText()
                                                                            .toUpperCase(), this.jTextFieldDomicilioNuevoMod
                                                                                                .getText()
                                                                                                .toUpperCase(),
                                                 this.jTextFieldMailNuevoMod
                                                                                                                    .getText()
                                                                                                                    .toUpperCase());
                        JOptionPane.showMessageDialog(null, "Los cambios se realizarion con exito");
                        this.limpiarModelo();
                    } catch (MailInvalidoException e) {
                        JOptionPane.showMessageDialog(null, "El mail ingresado es incorrecto");
                    } catch (NoExisteEntidadException e) {
                        //Nunca se dara, segun la implementacion de la vista, que el alumno no se encuentre registrado en la colecciones de facultad.
                    }
                }
            }else
                {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos porfavor");
                }   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un alumno","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConfirmarModActionPerformed

    private void jTextFieldLegajoConsultaaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldLegajoConsultaaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldLegajoConsultaaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldLegajoConsultaaActionPerformed

    private void jButtonConfirmarAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmarAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmarAltaActionPerformed
        // TODO add your handling code here:
        if(this.validarAlta())
        {
            String mail= this.jTextFieldMailAlta.getText();
            try {
                this.facultad.agregarAlumno(this.jTextFieldApellidoAlta
                                                .getText()
                                                .toUpperCase(), this.jTextFieldNombreAlta
                                                                    .getText()
                                                                    .toUpperCase(), this.jTextFieldDomicilioAlta
                                                                                        .getText()
                                                                                        .toUpperCase(),
                                            this.jTextFieldMailAlta.getText());
                JOptionPane.showMessageDialog(null, "El alumno fue creado con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
                this.limpiarTextFieldAlta();
            } catch (MailInvalidoException e) {
                JOptionPane.showMessageDialog(null, "El mail ingresado es incorrecto","Error en mail",JOptionPane.ERROR_MESSAGE);
            }
        }else
            {
                JOptionPane.showMessageDialog(null, "Complete todos los campos por favor","Error en los campos",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButtonConfirmarAltaActionPerformed

    private void jTextFieldNombreAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNombreAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNombreAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAltaActionPerformed

    private void jTextFieldApellidoAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldApellidoAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldApellidoAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoAltaActionPerformed

    private void jTextFieldDomicilioAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldDomicilioAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldDomicilioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDomicilioAltaActionPerformed

    private void jButtonBuscarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarBajaActionPerformed
        this.limpiarModelo();
        String nombre=this.jTextFieldNombreBaja.getText().toUpperCase();
        String apellido=this.jTextFieldApellidoBaja.getText().toUpperCase();
        ArrayList<Alumno> alumnos=facultad.buscarAlumnoPorNombre(nombre, apellido);;
        Iterator it=alumnos.iterator();
        
        while(it.hasNext())
        {
           Alumno a=(Alumno)it.next();
            modeloBaja.addElement(a);
        }
        this.jListAlumnosBaja.setModel(modeloBaja); 
    }//GEN-LAST:event_jButtonBuscarBajaActionPerformed

    private void jButtonVolverAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverAltaActionPerformed
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAltaActionPerformed

    public void cerrar() {
        try{
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e) {
                    ventana.setVisible(true);
                }
            });
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    private void jButtonEliminarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarBajaActionPerformed
        // TODO add your handling code here:
        int n=this.jListAlumnosBaja.getSelectedIndex();
        if(n!=-1) {
            Alumno a=(Alumno) this.modeloBaja.getElementAt(n);
            int valor=JOptionPane.showConfirmDialog(this,"¿Esta seguro que desea eliminar a "+a.getApellido()+"?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(valor==JOptionPane.YES_OPTION){
                try {
                    this.facultad.bajaAlumno(a.getLegajo());
                } catch (NoExisteEntidadException e) {
                }
                this.limpiarModelo();       
            }    
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un alumno","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarBajaActionPerformed

    private void jButtonVolverBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverBajaActionPerformed
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverBajaActionPerformed

    private void jButtonBuscarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarModActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarModActionPerformed
        // TODO add your handling code here
        this.limpiarModelo();
        String nombre=this.jTextFieldNombreMod.getText().toUpperCase();
        String apellido=this.jTextFieldApellidoMod.getText().toUpperCase();
        ArrayList<Alumno> alumnos=facultad.buscarAlumnoPorNombre(nombre, apellido);;
        Iterator it=alumnos.iterator();
        
        while(it.hasNext())
        {
           Alumno a=(Alumno)it.next();
            modeloMod.addElement(a);
        }
        this.jListAlumnosMod.setModel(modeloMod);
    }//GEN-LAST:event_jButtonBuscarModActionPerformed

    private void jButtonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarConsultaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        String nombre=this.jTextFieldNombreConsulta.getText().toUpperCase();
        String apellido=this.jTextFieldApellidoConsulta.getText().toUpperCase();
        ArrayList<Alumno> alumnos=facultad.buscarAlumnoPorNombre(nombre, apellido);;
        Iterator it=alumnos.iterator();
        
        while(it.hasNext())
        {
           Alumno a=(Alumno)it.next();
            modeloConsulta.addElement(a);
        }
        this.jListAlumnosConsulta.setModel(modeloConsulta);
    }//GEN-LAST:event_jButtonBuscarConsultaActionPerformed

    private void jButtonCargarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCargarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonCargarConsultaActionPerformed
        // TODO add your handling code here:
        this.jListAsignaturasAprobadasConsulta.clearSelection();
        int n=this.jListAlumnosConsulta.getSelectedIndex();
        if(n!=-1) {
            Alumno a=(Alumno) this.modeloConsulta.getElementAt(n);
            this.jTextFieldApellidoConsultaa.setText(a.getApellido());
            this.jTextFieldDomicilioConsulta.setText(a.getDomicilio());
            this.jTextFieldLegajoConsultaa.setText(a.getLegajo());
            this.jTextFieldMailConsulta.setText(a.getMail());
            this.jTextFieldNombreConsultaa.setText(a.getNombre());
            this.jListAlumnosConsulta.clearSelection();
            Hashtable<String,Asignatura> asignaturas=a.getHistoria();
            Enumeration e = asignaturas.elements();
            Asignatura asig;
            while( e.hasMoreElements() ){
                asig =(Asignatura) e.nextElement();
                this.modeloConsultaAsig.addElement(asig);
            }
            this.jListAsignaturasAprobadasConsulta.setModel(modeloConsultaAsig);   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un alumno","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarConsultaActionPerformed

    private void jButtonVolverConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverConsultaActionPerformed
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverConsultaActionPerformed

    private void jButtonVolverModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverModActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverModActionPerformed
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverModActionPerformed

    private void jButtonAsigAprobModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAsigAprobModActionPerformed
    {//GEN-HEADEREND:event_jButtonAsigAprobModActionPerformed
        // TODO add your handling code here:
        VentanaAltasBajasAsignaturasAlumno ven= new VentanaAltasBajasAsignaturasAlumno(this.facultad,this);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAsigAprobModActionPerformed

    private void jTextFieldMailConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    //new VentanaAlumno().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsigAprobMod;
    private javax.swing.JButton jButtonBuscarBaja;
    private javax.swing.JButton jButtonBuscarConsulta;
    private javax.swing.JButton jButtonBuscarMod;
    private javax.swing.JButton jButtonCargarConsulta;
    private javax.swing.JButton jButtonConfirmarAlta;
    private javax.swing.JButton jButtonConfirmarMod;
    private javax.swing.JButton jButtonEliminarBaja;
    private javax.swing.JButton jButtonVolverAlta;
    private javax.swing.JButton jButtonVolverBaja;
    private javax.swing.JButton jButtonVolverConsulta;
    private javax.swing.JButton jButtonVolverMod;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellidoAlta;
    private javax.swing.JLabel jLabelApellidoBaja;
    private javax.swing.JLabel jLabelApellidoConsulta;
    private javax.swing.JLabel jLabelApellidoMod;
    private javax.swing.JLabel jLabelApellidoNuevoMod;
    private javax.swing.JLabel jLabelDomicilioAlta;
    private javax.swing.JLabel jLabelDomicilioNuevoMod;
    private javax.swing.JLabel jLabelMailAlta;
    private javax.swing.JLabel jLabelMailNuevoMod;
    private javax.swing.JLabel jLabelNombreAlta;
    private javax.swing.JLabel jLabelNombreBaja;
    private javax.swing.JLabel jLabelNombreConsulta;
    private javax.swing.JLabel jLabelNombreMod;
    private javax.swing.JLabel jLabelNombreNuevoMod;
    private javax.swing.JList<String> jListAlumnosBaja;
    private javax.swing.JList<String> jListAlumnosConsulta;
    private javax.swing.JList<String> jListAlumnosMod;
    private javax.swing.JList<String> jListAsignaturasAprobadasConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelAltaAlumno;
    private javax.swing.JPanel jPanelBajaAlumno;
    private javax.swing.JPanel jPanelConsultaAlumno;
    private javax.swing.JPanel jPanelModAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldApellidoAlta;
    private javax.swing.JTextField jTextFieldApellidoBaja;
    private javax.swing.JTextField jTextFieldApellidoConsulta;
    private javax.swing.JTextField jTextFieldApellidoConsultaa;
    private javax.swing.JTextField jTextFieldApellidoMod;
    private javax.swing.JTextField jTextFieldApellidoNuevoMod;
    private javax.swing.JTextField jTextFieldDomicilioAlta;
    private javax.swing.JTextField jTextFieldDomicilioConsulta;
    private javax.swing.JTextField jTextFieldDomicilioNuevoMod;
    private javax.swing.JTextField jTextFieldLegajoConsultaa;
    private javax.swing.JTextField jTextFieldMailAlta;
    private javax.swing.JTextField jTextFieldMailConsulta;
    private javax.swing.JTextField jTextFieldMailNuevoMod;
    private javax.swing.JTextField jTextFieldNombreAlta;
    private javax.swing.JTextField jTextFieldNombreBaja;
    private javax.swing.JTextField jTextFieldNombreConsulta;
    private javax.swing.JTextField jTextFieldNombreConsultaa;
    private javax.swing.JTextField jTextFieldNombreMod;
    private javax.swing.JTextField jTextFieldNombreNuevoMod;
    // End of variables declaration//GEN-END:variables

}
