
package Visual;

import java.awt.event.WindowAdapter;

import java.awt.event.WindowEvent;

import java.util.ArrayList;

import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import sistemaeducativo.Alumno;
import sistemaeducativo.Facultad;

/**
 *
 * @author Usuario
 */
public class VentanaAlumno extends javax.swing.JFrame
    
{
    private Facultad facultad;
    private DefaultListModel modelo;
    private VentanaPrincipal ventana;
    
    /** Creates new form VentanaAlumno */
    public VentanaAlumno(Facultad facultad, VentanaPrincipal ventana)
    {
        initComponents();
        this.facultad=facultad;
        this.ventana=ventana;
        this.cerrar();
        setResizable(false);
        setTitle("Sistema Educativo -Alumno");
        setLocationRelativeTo(null);
        this.modelo=new DefaultListModel();
        
    }
    public void limpiarModelo()
    {
        this.modelo.clear();
    }
    public void limpiarTextFieldAlta()
    {
        this.jTextFieldApellidoAlta.setText("");
        this.jTextFieldNombreAlta.setText("");
        this.jTextFieldMailAlta.setText("");
        this.jTextFieldDomicilioAlta.setText("");
    }
    public boolean validarAlta()
    {
        if(this.jTextFieldApellidoAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldNombreAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldMailAlta.getText().equals(""))
        {
            return false;
        }
        if(this.jTextFieldDomicilioAlta.getText().equals(""))
        {
            return false;
        }
        return true;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelAltaAlumno = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelNombreAlta = new javax.swing.JLabel();
        jTextFieldNombreAlta = new javax.swing.JTextField();
        jLabelApellidoAlta = new javax.swing.JLabel();
        jTextFieldApellidoAlta = new javax.swing.JTextField();
        jLabelDomicilioAlta = new javax.swing.JLabel();
        jTextFieldDomicilioAlta = new javax.swing.JTextField();
        jLabelMailAlta = new javax.swing.JLabel();
        jTextFieldMailAlta = new javax.swing.JTextField();
        jButtonVolverAlta = new javax.swing.JButton();
        jButtonConfirmarAlta = new javax.swing.JButton();
        jPanelBajaAlumno = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombreBaja = new javax.swing.JLabel();
        jTextFieldNombreBaja = new javax.swing.JTextField();
        jLabelApellidoBaja = new javax.swing.JLabel();
        jTextFieldApellidoBaja = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelSeleccionarBaja = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlumnosBaja = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jButtonVolverBaja = new javax.swing.JButton();
        jButtonEliminarBaja = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonBuscarBaja = new javax.swing.JButton();
        jPanelModAlumno = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNombreMod = new javax.swing.JLabel();
        jTextFieldNombreMod = new javax.swing.JTextField();
        jLabelApellidoMod = new javax.swing.JLabel();
        jTextFieldApellidoMod = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabelSeleccionarMod = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAlumnosMod = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabelNombreNuevoMod = new javax.swing.JLabel();
        jTextFieldNombreNuevoMod = new javax.swing.JTextField();
        jLabelApellidoNuevoMod = new javax.swing.JLabel();
        jTextFieldApellidoNuevoMod = new javax.swing.JTextField();
        jLabelMailNuevoMod = new javax.swing.JLabel();
        jTextFieldMailNuevoMod = new javax.swing.JTextField();
        jLabelDomicilioNuevoMod = new javax.swing.JLabel();
        jTextFieldDomicilioNuevoMod = new javax.swing.JTextField();
        jButtonVolverMod = new javax.swing.JButton();
        jButtonConfirmarMod = new javax.swing.JButton();
        jButtonAsigAprobMod = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonBuscarMod = new javax.swing.JButton();
        jPanelConsultaAlumno = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabelNombreConsulta = new javax.swing.JLabel();
        jTextFieldNombreConsulta = new javax.swing.JTextField();
        jLabelApellidoConsulta = new javax.swing.JLabel();
        jTextFieldApellidoConsulta = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jButtonBuscarConsulta = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabelSeleccionarConsulta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAlumnosConsulta = new javax.swing.JList<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldLegajoConsultaa = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldNombreConsultaa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldApellidoConsultaa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldDomicilioConsulta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldMailConsulta = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAsignaturasAprobadasConsulta = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jButtonCargarConsulta = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButtonVolverConsulta = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(5, 2));

        jLabelNombreAlta.setText("Nombre");
        jPanel5.add(jLabelNombreAlta);

        jTextFieldNombreAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldNombreAlta);

        jLabelApellidoAlta.setText("Apellido");
        jPanel5.add(jLabelApellidoAlta);

        jTextFieldApellidoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldApellidoAlta);

        jLabelDomicilioAlta.setText("Domicilio");
        jPanel5.add(jLabelDomicilioAlta);

        jTextFieldDomicilioAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDomicilioAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldDomicilioAlta);

        jLabelMailAlta.setText("Mail");
        jPanel5.add(jLabelMailAlta);

        jTextFieldMailAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jTextFieldMailAlta);

        jButtonVolverAlta.setText("Volver");
        jButtonVolverAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonVolverAlta);

        jButtonConfirmarAlta.setText("Confirmar Alta");
        jButtonConfirmarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarAltaActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonConfirmarAlta);

        javax.swing.GroupLayout jPanelAltaAlumnoLayout = new javax.swing.GroupLayout(jPanelAltaAlumno);
        jPanelAltaAlumno.setLayout(jPanelAltaAlumnoLayout);
        jPanelAltaAlumnoLayout.setHorizontalGroup(
            jPanelAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanelAltaAlumnoLayout.setVerticalGroup(
            jPanelAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Alta", jPanelAltaAlumno);

        jPanelBajaAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabelNombreBaja.setText("Nombre del alumno a dar de baja");
        jPanel1.add(jLabelNombreBaja);
        jPanel1.add(jTextFieldNombreBaja);

        jLabelApellidoBaja.setText("Apellido del alumno a dar de baja");
        jPanel1.add(jLabelApellidoBaja);
        jPanel1.add(jTextFieldApellidoBaja);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabelSeleccionarBaja.setText("Seleccione el alumno a eliminar");
        jPanel2.add(jLabelSeleccionarBaja);

        jScrollPane1.setViewportView(jListAlumnosBaja);

        jPanel2.add(jScrollPane1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolverBaja.setText("volver");
        jPanel3.add(jButtonVolverBaja);

        jButtonEliminarBaja.setText("eliminar alumno ");
        jButtonEliminarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarBajaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEliminarBaja);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarBaja.setText("Buscar");
        jButtonBuscarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarBajaActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonBuscarBaja);

        javax.swing.GroupLayout jPanelBajaAlumnoLayout = new javax.swing.GroupLayout(jPanelBajaAlumno);
        jPanelBajaAlumno.setLayout(jPanelBajaAlumnoLayout);
        jPanelBajaAlumnoLayout.setHorizontalGroup(
            jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBajaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBajaAlumnoLayout.setVerticalGroup(
            jPanelBajaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajaAlumnoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Baja", jPanelBajaAlumno);

        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jLabelNombreMod.setText("Nombre del alumno ");
        jPanel4.add(jLabelNombreMod);
        jPanel4.add(jTextFieldNombreMod);

        jLabelApellidoMod.setText("Apellido del alumno ");
        jPanel4.add(jLabelApellidoMod);
        jPanel4.add(jTextFieldApellidoMod);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabelSeleccionarMod.setText("Seleccione el alumno ");
        jPanel6.add(jLabelSeleccionarMod);

        jScrollPane2.setViewportView(jListAlumnosMod);

        jPanel6.add(jScrollPane2);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridLayout(6, 2));

        jLabelNombreNuevoMod.setText("Nombre nuevo");
        jPanel7.add(jLabelNombreNuevoMod);
        jPanel7.add(jTextFieldNombreNuevoMod);

        jLabelApellidoNuevoMod.setText("Apellido nuevo");
        jPanel7.add(jLabelApellidoNuevoMod);
        jPanel7.add(jTextFieldApellidoNuevoMod);

        jLabelMailNuevoMod.setText("Mail nuevo");
        jPanel7.add(jLabelMailNuevoMod);
        jPanel7.add(jTextFieldMailNuevoMod);

        jLabelDomicilioNuevoMod.setText("Domicilio nuevo");
        jPanel7.add(jLabelDomicilioNuevoMod);
        jPanel7.add(jTextFieldDomicilioNuevoMod);

        jButtonVolverMod.setText("Volver");
        jPanel7.add(jButtonVolverMod);

        jButtonConfirmarMod.setText("Confirmar Cambios");
        jButtonConfirmarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarModActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonConfirmarMod);

        jButtonAsigAprobMod.setText("Altas/Bajas de Asignaturas Aprobadas");
        jPanel7.add(jButtonAsigAprobMod);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarMod.setText("Buscar");
        jPanel9.add(jButtonBuscarMod);

        javax.swing.GroupLayout jPanelModAlumnoLayout = new javax.swing.GroupLayout(jPanelModAlumno);
        jPanelModAlumno.setLayout(jPanelModAlumnoLayout);
        jPanelModAlumnoLayout.setHorizontalGroup(
            jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );
        jPanelModAlumnoLayout.setVerticalGroup(
            jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModAlumnoLayout.createSequentialGroup()
                .addGap(0, 284, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 474, Short.MAX_VALUE)))
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(292, Short.MAX_VALUE)))
            .addGroup(jPanelModAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModAlumnoLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(450, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Modificaciones", jPanelModAlumno);

        jPanel10.setLayout(new java.awt.GridLayout(2, 2));

        jLabelNombreConsulta.setText("Nombre del alumno ");
        jPanel10.add(jLabelNombreConsulta);
        jPanel10.add(jTextFieldNombreConsulta);

        jLabelApellidoConsulta.setText("Apellido del alumno ");
        jPanel10.add(jLabelApellidoConsulta);
        jPanel10.add(jTextFieldApellidoConsulta);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarConsulta.setText("Buscar");
        jPanel11.add(jButtonBuscarConsulta);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        jLabelSeleccionarConsulta.setText("Seleccione el alumno ");
        jPanel12.add(jLabelSeleccionarConsulta);

        jListAlumnosConsulta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListAlumnosConsulta);

        jPanel12.add(jScrollPane3);

        jPanel13.setLayout(new java.awt.GridLayout(5, 2));

        jLabel19.setText("Legajo");
        jPanel13.add(jLabel19);

        jTextFieldLegajoConsultaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLegajoConsultaaActionPerformed(evt);
            }
        });
        jPanel13.add(jTextFieldLegajoConsultaa);

        jLabel21.setText("Nombre");
        jPanel13.add(jLabel21);
        jPanel13.add(jTextFieldNombreConsultaa);

        jLabel20.setText("Apellido");
        jPanel13.add(jLabel20);
        jPanel13.add(jTextFieldApellidoConsultaa);

        jLabel23.setText("Domicilio");
        jPanel13.add(jLabel23);
        jPanel13.add(jTextFieldDomicilioConsulta);

        jLabel22.setText("Mail");
        jPanel13.add(jLabel22);
        jPanel13.add(jTextFieldMailConsulta);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jListAsignaturasAprobadasConsulta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListAsignaturasAprobadasConsulta);

        jLabel24.setText("Asignaturas Aprobadas");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jButtonCargarConsulta.setText("Cargar");

        jButtonVolverConsulta.setText("volver");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jButtonVolverConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolverConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelConsultaAlumnoLayout = new javax.swing.GroupLayout(jPanelConsultaAlumno);
        jPanelConsultaAlumno.setLayout(jPanelConsultaAlumnoLayout);
        jPanelConsultaAlumnoLayout.setHorizontalGroup(
            jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaAlumnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaAlumnoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCargarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        jPanelConsultaAlumnoLayout.setVerticalGroup(
            jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaAlumnoLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonCargarConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(455, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(424, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaAlumnoLayout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Consulta", jPanelConsultaAlumno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }//GEN-END:initComponents

    private void jTextFieldMailAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldMailAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldMailAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailAltaActionPerformed

    private void jButtonConfirmarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmarModActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmarModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmarModActionPerformed

    private void jTextFieldLegajoConsultaaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldLegajoConsultaaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldLegajoConsultaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLegajoConsultaaActionPerformed

    private void jButtonConfirmarAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmarAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmarAltaActionPerformed
        // TODO add your handling code here:
        if(this.validarAlta())
        {
            String mail= this.jTextFieldMailAlta.getText();
            if(mail.contains("@")&& (mail.indexOf("@") <(mail.length()-1)) && (mail.indexOf("@")>0))
            {
                this.facultad.agregarAlumno(this.jTextFieldApellidoAlta.getText().toUpperCase(), this.jTextFieldNombreAlta.getText().toUpperCase(), this.jTextFieldDomicilioAlta.getText().toUpperCase(), this.jTextFieldMailAlta.getText());
                JOptionPane.showMessageDialog(null, "El alumno fue creado con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
                this.limpiarTextFieldAlta();
                
            }else
            {
                JOptionPane.showMessageDialog(null, "El mail ingresado es incorrecto","Error en mail",JOptionPane.ERROR_MESSAGE);
            }
        }else
            {
                JOptionPane.showMessageDialog(null, "Complete todos los campos por favor","Error en los campos",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButtonConfirmarAltaActionPerformed

    private void jTextFieldNombreAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNombreAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNombreAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreAltaActionPerformed

    private void jTextFieldApellidoAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldApellidoAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldApellidoAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoAltaActionPerformed

    private void jTextFieldDomicilioAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldDomicilioAltaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldDomicilioAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDomicilioAltaActionPerformed

    private void jButtonBuscarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarBajaActionPerformed
        this.limpiarModelo();
        String nombre=this.jTextFieldNombreBaja.getText().toUpperCase();
        String apellido=this.jTextFieldApellidoBaja.getText().toUpperCase();
        ArrayList<Alumno> alumnos=facultad.buscarAlumnoPorNombre(nombre, apellido);;
        Iterator it=alumnos.iterator();
        
        while(it.hasNext())
        {
           Alumno a=(Alumno)it.next();
            modelo.addElement(a);
        }
        this.jListAlumnosBaja.setModel(modelo); 
    }//GEN-LAST:event_jButtonBuscarBajaActionPerformed

    private void jButtonVolverAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverAltaActionPerformed
        this.setVisible(false);
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAltaActionPerformed

    public void cerrar() {
        try{
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e) {
                    ventana.setVisible(true);
                }
            });
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    private void jButtonEliminarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarBajaActionPerformed
        // TODO add your handling code here:
        int n=this.jListAlumnosBaja.getSelectedIndex();
        Alumno a=(Alumno) this.modelo.getElementAt(n);
        this.facultad.bajaAlumno(a.getLegajo());
        this.limpiarModelo();
    }//GEN-LAST:event_jButtonEliminarBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAlumno.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    //new VentanaAlumno().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsigAprobMod;
    private javax.swing.JButton jButtonBuscarBaja;
    private javax.swing.JButton jButtonBuscarConsulta;
    private javax.swing.JButton jButtonBuscarMod;
    private javax.swing.JButton jButtonCargarConsulta;
    private javax.swing.JButton jButtonConfirmarAlta;
    private javax.swing.JButton jButtonConfirmarMod;
    private javax.swing.JButton jButtonEliminarBaja;
    private javax.swing.JButton jButtonVolverAlta;
    private javax.swing.JButton jButtonVolverBaja;
    private javax.swing.JButton jButtonVolverConsulta;
    private javax.swing.JButton jButtonVolverMod;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellidoAlta;
    private javax.swing.JLabel jLabelApellidoBaja;
    private javax.swing.JLabel jLabelApellidoConsulta;
    private javax.swing.JLabel jLabelApellidoMod;
    private javax.swing.JLabel jLabelApellidoNuevoMod;
    private javax.swing.JLabel jLabelDomicilioAlta;
    private javax.swing.JLabel jLabelDomicilioNuevoMod;
    private javax.swing.JLabel jLabelMailAlta;
    private javax.swing.JLabel jLabelMailNuevoMod;
    private javax.swing.JLabel jLabelNombreAlta;
    private javax.swing.JLabel jLabelNombreBaja;
    private javax.swing.JLabel jLabelNombreConsulta;
    private javax.swing.JLabel jLabelNombreMod;
    private javax.swing.JLabel jLabelNombreNuevoMod;
    private javax.swing.JLabel jLabelSeleccionarBaja;
    private javax.swing.JLabel jLabelSeleccionarConsulta;
    private javax.swing.JLabel jLabelSeleccionarMod;
    private javax.swing.JList<String> jListAlumnosBaja;
    private javax.swing.JList<String> jListAlumnosConsulta;
    private javax.swing.JList<String> jListAlumnosMod;
    private javax.swing.JList<String> jListAsignaturasAprobadasConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAltaAlumno;
    private javax.swing.JPanel jPanelBajaAlumno;
    private javax.swing.JPanel jPanelConsultaAlumno;
    private javax.swing.JPanel jPanelModAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldApellidoAlta;
    private javax.swing.JTextField jTextFieldApellidoBaja;
    private javax.swing.JTextField jTextFieldApellidoConsulta;
    private javax.swing.JTextField jTextFieldApellidoConsultaa;
    private javax.swing.JTextField jTextFieldApellidoMod;
    private javax.swing.JTextField jTextFieldApellidoNuevoMod;
    private javax.swing.JTextField jTextFieldDomicilioAlta;
    private javax.swing.JTextField jTextFieldDomicilioConsulta;
    private javax.swing.JTextField jTextFieldDomicilioNuevoMod;
    private javax.swing.JTextField jTextFieldLegajoConsultaa;
    private javax.swing.JTextField jTextFieldMailAlta;
    private javax.swing.JTextField jTextFieldMailConsulta;
    private javax.swing.JTextField jTextFieldMailNuevoMod;
    private javax.swing.JTextField jTextFieldNombreAlta;
    private javax.swing.JTextField jTextFieldNombreBaja;
    private javax.swing.JTextField jTextFieldNombreConsulta;
    private javax.swing.JTextField jTextFieldNombreConsultaa;
    private javax.swing.JTextField jTextFieldNombreMod;
    private javax.swing.JTextField jTextFieldNombreNuevoMod;
    // End of variables declaration//GEN-END:variables

}
