
package Visual;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.ArrayList;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;

import java.util.Map;
import java.util.TreeMap;

import javax.swing.DefaultListModel;

import javax.swing.JFrame;

import javax.swing.JOptionPane;

import sistemaeducativo.Alumno;
import sistemaeducativo.Asignatura;
import sistemaeducativo.AsignaturaAprobadaYaRegistradaException;
import sistemaeducativo.CorrelativaRegistradaException;
import sistemaeducativo.Cursada;
import sistemaeducativo.Facultad;

/**
 *
 * @author Usuario
 */
public class VentanaAsignatura extends javax.swing.JFrame
{

    /** Creates new form VentanaAsignatura */
    private Facultad facultad;
    private VentanaPrincipal ventana;
    private DefaultListModel modeloBaja;
    private DefaultListModel modeloMod;
    private DefaultListModel modeloModAlta;
    private DefaultListModel modeloModBaja;
    private DefaultListModel modeloConsulta;
    private DefaultListModel modeloConsultaCorrelativas;
    public VentanaAsignatura(Facultad facultad,VentanaPrincipal ventana)
    {
        initComponents();
        this.facultad=facultad;
        this.ventana=ventana;
        this.cerrar();
        setResizable(false);
        setTitle("Sistema Educativo -Asignatura");
        setLocationRelativeTo(null);
        //this.setSize(480,572);
        this.modeloBaja=new DefaultListModel();
        this.modeloModAlta=new DefaultListModel();
        this.modeloModBaja=new DefaultListModel();
        this.modeloMod=new DefaultListModel();
        this.modeloConsulta=new DefaultListModel();
        this.modeloConsultaCorrelativas=new DefaultListModel();
    }
    public void cerrar() {
        try{
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e) {
                    ventana.setVisible(true);
                }
            });
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void limpiarModelo()
    {
        this.modeloConsultaCorrelativas.clear();
        this.modeloConsulta.clear();
        this.modeloModBaja.clear();
        this.modeloModAlta.clear();
        this.modeloBaja.clear();
        this.modeloMod.clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAlta = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreAlta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonVolverAlta = new javax.swing.JButton();
        jButtonCrearAsignaturaAlta = new javax.swing.JButton();
        jPanelBaja = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreBaja = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarBaja = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBaja = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonVolverBaja = new javax.swing.JButton();
        jButtonEliminarBaja = new javax.swing.JButton();
        jPanelMod = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAsignaturasMod = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreMod = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jButtonVolver1Mod = new javax.swing.JButton();
        jButtonEliminarMod = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonBuscarMod = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreNuevoMod = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButtonCargarMod = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAgregarCorrelativaMod = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListEliminarCorrelativaMod = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButtonVolver2Mod = new javax.swing.JButton();
        jButtonAgregarMod = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButtonCambiarNombreMod = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNombreConsulta = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jButtonBuscarConsulta = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAsignaturaConsulta = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jButtonCargarConsulta = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNombreeConsulta = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIdConsulta = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListCorrelativasConsulta = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jButtonVolverConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jPanel2.add(jTextFieldNombreAlta);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolverAlta.setText("volver");
        jButtonVolverAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAltaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonVolverAlta);

        jButtonCrearAsignaturaAlta.setText("Crear Asignatura");
        jButtonCrearAsignaturaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAsignaturaAltaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCrearAsignaturaAlta);

        javax.swing.GroupLayout jPanelAltaLayout = new javax.swing.GroupLayout(jPanelAlta);
        jPanelAlta.setLayout(jPanelAltaLayout);
        jPanelAltaLayout.setHorizontalGroup(
            jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAltaLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAltaLayout.setVerticalGroup(
            jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alta", jPanelAlta);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Nombre");
        jPanel4.add(jLabel2);
        jPanel4.add(jTextFieldNombreBaja);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarBaja.setText("Buscar");
        jButtonBuscarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarBajaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarBaja);

        jScrollPane1.setViewportView(jListBaja);

        jLabel3.setText("Seleccione la Asignatura a eliminar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolverBaja.setText("Volver");
        jButtonVolverBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverBajaActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonVolverBaja);

        jButtonEliminarBaja.setText("Eliminar");
        jButtonEliminarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarBajaActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonEliminarBaja);

        javax.swing.GroupLayout jPanelBajaLayout = new javax.swing.GroupLayout(jPanelBaja);
        jPanelBaja.setLayout(jPanelBajaLayout);
        jPanelBajaLayout.setHorizontalGroup(
            jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajaLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBajaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelBajaLayout.setVerticalGroup(
            jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBajaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(500, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Baja", jPanelBaja);

        jScrollPane2.setViewportView(jListAsignaturasMod);

        jLabel5.setText("Seleccione la Asignatura a modificar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addContainerGap(290, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setText("Nombre");
        jPanel8.add(jLabel4);
        jPanel8.add(jTextFieldNombreMod);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolver1Mod.setText("Volver");
        jButtonVolver1Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ModActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonVolver1Mod);

        jButtonEliminarMod.setText("Eliminar");
        jButtonEliminarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarModActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonEliminarMod);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarMod.setText("Buscar");
        jButtonBuscarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarModActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonBuscarMod);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.GridLayout());

        jLabel6.setText("Nombre Nuevo");
        jPanel12.add(jLabel6);
        jPanel12.add(jTextFieldNombreNuevoMod);

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCargarMod.setText("Cargar");
        jButtonCargarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarModActionPerformed(evt);
            }
        });
        jPanel13.add(jButtonCargarMod);

        jScrollPane4.setViewportView(jListAgregarCorrelativaMod);

        jLabel7.setText("Agregar Correlativa");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap(114, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jScrollPane5.setViewportView(jListEliminarCorrelativaMod);

        jLabel8.setText("Eliminar correlativa");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addContainerGap(134, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolver2Mod.setText("Volver");
        jButtonVolver2Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ModActionPerformed(evt);
            }
        });
        jPanel17.add(jButtonVolver2Mod);

        jButtonAgregarMod.setText("Agregar");
        jButtonAgregarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarModActionPerformed(evt);
            }
        });
        jPanel17.add(jButtonAgregarMod);

        jPanel18.setLayout(new java.awt.GridLayout());

        jButtonCambiarNombreMod.setText("Cambiar Nombre");
        jButtonCambiarNombreMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarNombreModActionPerformed(evt);
            }
        });
        jPanel18.add(jButtonCambiarNombreMod);

        javax.swing.GroupLayout jPanelModLayout = new javax.swing.GroupLayout(jPanelMod);
        jPanelMod.setLayout(jPanelModLayout);
        jPanelModLayout.setHorizontalGroup(
            jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelModLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                    .addContainerGap(254, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(268, Short.MAX_VALUE)))
        );
        jPanelModLayout.setVerticalGroup(
            jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(500, Short.MAX_VALUE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(323, Short.MAX_VALUE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                    .addGap(0, 501, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModLayout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(253, Short.MAX_VALUE)))
            .addGroup(jPanelModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModLayout.createSequentialGroup()
                    .addGap(0, 502, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Modificaciones", jPanelMod);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel9.setText("Nombre");
        jPanel7.add(jLabel9);
        jPanel7.add(jTextFieldNombreConsulta);

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarConsulta.setText("Buscar");
        jButtonBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarConsultaActionPerformed(evt);
            }
        });
        jPanel19.add(jButtonBuscarConsulta);

        jScrollPane6.setViewportView(jListAsignaturaConsulta);

        jLabel10.setText("Seleccione la Asignatura a eliminar");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addContainerGap(297, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jButtonCargarConsulta.setText("Cargar");
        jButtonCargarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarConsultaActionPerformed(evt);
            }
        });

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setText("Nombre");
        jPanel23.add(jLabel11);
        jPanel23.add(jTextFieldNombreeConsulta);

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setText("ID");
        jPanel24.add(jLabel12);
        jPanel24.add(jTextFieldIdConsulta);

        jScrollPane7.setViewportView(jListCorrelativasConsulta);

        jLabel13.setText("Lista de correlativas");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        jButtonVolverConsulta.setText("Volver");
        jButtonVolverConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverConsultaActionPerformed(evt);
            }
        });
        jPanel22.add(jButtonVolverConsulta);

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConsultaLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButtonCargarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCargarConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(500, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap(312, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(200, 200, 200)))
        );

        jTabbedPane1.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void jButtonCrearAsignaturaAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCrearAsignaturaAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonCrearAsignaturaAltaActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldNombreAlta.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Complete todos los campos por favor","Error en los campos",JOptionPane.ERROR_MESSAGE);
            
        }else
        {
            this.facultad.agregarAsignatura(this.jTextFieldNombreAlta.getText().toUpperCase());
            JOptionPane.showMessageDialog(null,"La asignatura fue creada con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCrearAsignaturaAltaActionPerformed

    private void jButtonVolverAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverAltaActionPerformed
        // TODO add your handling code here:
        this.ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonVolverAltaActionPerformed

    private void jButtonBuscarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarBajaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Asignatura> asignaturas=this.facultad.buscarAsignaturaPorNombre(this.jTextFieldNombreBaja.getText().toUpperCase());
        Iterator it=asignaturas.iterator();
        
        while(it.hasNext())
        {
           Asignatura a=(Asignatura)it.next();
            modeloBaja.addElement(a);
        }
        this.jListBaja.setModel(modeloBaja); 
    }//GEN-LAST:event_jButtonBuscarBajaActionPerformed

    private void jButtonEliminarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarBajaActionPerformed
        // TODO add your handling code here:
        int n=this.jListBaja.getSelectedIndex();
        if(n!=-1) {
            Asignatura a=(Asignatura) this.modeloBaja.getElementAt(n);
            this.facultad.bajaAsignatura(a);
            this.limpiarModelo();
            JOptionPane.showMessageDialog(null,"La asignatura fue eliminada con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un alumno","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarBajaActionPerformed

    private void jButtonVolverBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverBajaActionPerformed
        // TODO add your handling code here:
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverBajaActionPerformed

    private void jButtonCargarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCargarModActionPerformed
    {//GEN-HEADEREND:event_jButtonCargarModActionPerformed
        // TODO add your handling code here:
        int n=this.jListAsignaturasMod.getSelectedIndex();
        if(n!=-1){
            Asignatura a=(Asignatura) this.modeloMod.getElementAt(n);
            TreeMap<String,Asignatura> asignaturas=this.facultad.getAsignaturas();
            Iterator it = asignaturas.entrySet().iterator();
            while (it.hasNext()) {
                Asignatura asig;
                Map.Entry m = (Map.Entry) it.next();
                asig = (Asignatura) m.getValue();
                if(asig!=a)
                {
                    this.modeloModAlta.addElement(asig);    
                }
            }
            this.jListAgregarCorrelativaMod.setModel(modeloModAlta);
            
            Hashtable<String,Asignatura> asignaturas2=a.getCorrelatividades();
            Enumeration e = asignaturas2.elements();
            
            while( e.hasMoreElements() ){
            Asignatura asig;
              asig =(Asignatura) e.nextElement();
              this.modeloModBaja.addElement(asig);
            }
            this.jListEliminarCorrelativaMod.setModel(modeloModBaja);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una asignatura","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonCargarModActionPerformed

    private void jButtonBuscarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarModActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarModActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Asignatura> asignaturas=this.facultad.buscarAsignaturaPorNombre(this.jTextFieldNombreMod.getText().toUpperCase());
        Iterator it=asignaturas.iterator();
        while(it.hasNext())
        {
           Asignatura a=(Asignatura)it.next();
            modeloMod.addElement(a);
        }
        this.jListAsignaturasMod.setModel(modeloMod); 
    }//GEN-LAST:event_jButtonBuscarModActionPerformed

    private void jButtonAgregarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonAgregarModActionPerformed
    {//GEN-HEADEREND:event_jButtonAgregarModActionPerformed
        // TODO add your handling code here:
        int n=this.jListAsignaturasMod.getSelectedIndex();
        if(n!=-1){
            Asignatura a1=(Asignatura) this.modeloMod.getElementAt(n);
            int x=this.jListAgregarCorrelativaMod.getSelectedIndex();
            Asignatura a2=(Asignatura) this.modeloModAlta.getElementAt(x);
            try
            {
                this.facultad.agregarCorrelativaAsignatura(a1, a2);
                JOptionPane.showMessageDialog(null, "La correlativa se añadio con exito");
            } catch (CorrelativaRegistradaException e)
            {
                JOptionPane.showMessageDialog(null, "La correlativa ya se encuentra registrada");
            }
            this.limpiarModelo();   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una asignatura","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarModActionPerformed

    private void jButtonEliminarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarModActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarModActionPerformed
        // TODO add your handling code here:
        int n=this.jListAsignaturasMod.getSelectedIndex();
        if(n!=-1){
            Asignatura a1=(Asignatura) this.modeloMod.getElementAt(n);
            int x=this.jListEliminarCorrelativaMod.getSelectedIndex();
            Asignatura a2=(Asignatura) this.modeloModBaja.getElementAt(x);
            this.facultad.eliminarCorrelativaAsignatura(a1, a2);
            JOptionPane.showMessageDialog(null, "La correlativa se elimino con exito");
            this.limpiarModelo();   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una asignatura","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarModActionPerformed

    private void jButtonVolver2ModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolver2ModActionPerformed
    {//GEN-HEADEREND:event_jButtonVolver2ModActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.ventana.setVisible(true);
    }//GEN-LAST:event_jButtonVolver2ModActionPerformed

    private void jButtonVolver1ModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolver1ModActionPerformed
    {//GEN-HEADEREND:event_jButtonVolver1ModActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.ventana.setVisible(true);
    }//GEN-LAST:event_jButtonVolver1ModActionPerformed

    private void jButtonCambiarNombreModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCambiarNombreModActionPerformed
    {//GEN-HEADEREND:event_jButtonCambiarNombreModActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldNombreNuevoMod.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Complete el campo por favor","Error en los campos",JOptionPane.ERROR_MESSAGE);
            
        }else
        {
            int n=this.jListAsignaturasMod.getSelectedIndex();
            Asignatura a1=(Asignatura) this.modeloMod.getElementAt(n);
            a1.setNombre(this.jTextFieldNombreNuevoMod.getText().toUpperCase());
            JOptionPane.showMessageDialog(null,"La asignatura fue modificada con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCambiarNombreModActionPerformed

    private void jButtonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarConsultaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Asignatura> asignaturas=this.facultad.buscarAsignaturaPorNombre(this.jTextFieldNombreConsulta.getText().toUpperCase());
        Iterator it=asignaturas.iterator();
        
        while(it.hasNext())
        {
           Asignatura a=(Asignatura)it.next();
            modeloConsulta.addElement(a);
        }
        this.jListAsignaturaConsulta.setModel(modeloConsulta); 
    }//GEN-LAST:event_jButtonBuscarConsultaActionPerformed

    private void jButtonCargarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCargarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonCargarConsultaActionPerformed
        // TODO add your handling code here:
        int n=this.jListAsignaturaConsulta.getSelectedIndex();
        if(n!=-1){
            Asignatura a=(Asignatura) this.modeloConsulta.getElementAt(n);
            this.jTextFieldIdConsulta.setText(a.getId());
            this.jTextFieldNombreeConsulta.setText(a.getNombre());
            Hashtable<String,Asignatura> asignaturas=a.getCorrelatividades();
            Enumeration e = asignaturas.elements();
            Asignatura asig;
            while( e.hasMoreElements() ){
                asig =(Asignatura) e.nextElement();
                this.modeloConsultaCorrelativas.addElement(asig);
            }
            this.jListCorrelativasConsulta.setModel(modeloConsultaCorrelativas);   
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una asignatura","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarConsultaActionPerformed

    private void jButtonVolverConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverConsultaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.ventana.setVisible(true);
    }//GEN-LAST:event_jButtonVolverConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAsignatura.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAsignatura.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAsignatura.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaAsignatura.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                   // new VentanaAsignatura().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMod;
    private javax.swing.JButton jButtonBuscarBaja;
    private javax.swing.JButton jButtonBuscarConsulta;
    private javax.swing.JButton jButtonBuscarMod;
    private javax.swing.JButton jButtonCambiarNombreMod;
    private javax.swing.JButton jButtonCargarConsulta;
    private javax.swing.JButton jButtonCargarMod;
    private javax.swing.JButton jButtonCrearAsignaturaAlta;
    private javax.swing.JButton jButtonEliminarBaja;
    private javax.swing.JButton jButtonEliminarMod;
    private javax.swing.JButton jButtonVolver1Mod;
    private javax.swing.JButton jButtonVolver2Mod;
    private javax.swing.JButton jButtonVolverAlta;
    private javax.swing.JButton jButtonVolverBaja;
    private javax.swing.JButton jButtonVolverConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListAgregarCorrelativaMod;
    private javax.swing.JList<String> jListAsignaturaConsulta;
    private javax.swing.JList<String> jListAsignaturasMod;
    private javax.swing.JList<String> jListBaja;
    private javax.swing.JList<String> jListCorrelativasConsulta;
    private javax.swing.JList<String> jListEliminarCorrelativaMod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAlta;
    private javax.swing.JPanel jPanelBaja;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelMod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldIdConsulta;
    private javax.swing.JTextField jTextFieldNombreAlta;
    private javax.swing.JTextField jTextFieldNombreBaja;
    private javax.swing.JTextField jTextFieldNombreConsulta;
    private javax.swing.JTextField jTextFieldNombreMod;
    private javax.swing.JTextField jTextFieldNombreNuevoMod;
    private javax.swing.JTextField jTextFieldNombreeConsulta;
    // End of variables declaration//GEN-END:variables

}
