
package Visual;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.ArrayList;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

import sistemaeducativo.Alumno;
import sistemaeducativo.Asignatura;
import sistemaeducativo.Cursada;
import sistemaeducativo.Facultad;
import sistemaeducativo.Fecha;
import sistemaeducativo.Profesor;

/**
 *
 * @author Usuario
 */
public class VentanaCursada extends javax.swing.JFrame
{

    /** Creates new form VentanaCursada */
    private Facultad facultad;
    private VentanaPrincipal ventana;
    private DefaultListModel modeloAlta;
    private DefaultListModel modeloBaja;
    private DefaultListModel modeloCursadaMod;
    private DefaultListModel modeloAsignaturaMod;
    private DefaultListModel modeloCursadaConsulta;
    private DefaultListModel modeloAlumnoConsulta;
    private DefaultListModel modeloProfesorConsulta;
    private DefaultListModel modeloHorariosConsulta;
    public VentanaCursada(Facultad f, VentanaPrincipal ventana)
    {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        facultad=f;
        this.ventana=ventana;
        this.cerrar();
        setResizable(false);
        setTitle("Sistema Educativo -Cursada");
        setLocationRelativeTo(null);
        this.modeloAlta=new DefaultListModel();
        this.modeloBaja=new DefaultListModel();
        this.modeloCursadaMod=new DefaultListModel();
        this.modeloAsignaturaMod=new DefaultListModel();
        this.modeloCursadaConsulta=new DefaultListModel();
        this.modeloAlumnoConsulta=new DefaultListModel();
        this.modeloHorariosConsulta=new DefaultListModel();
        this.modeloProfesorConsulta=new DefaultListModel();
    }
    public void limpiarModelo()
    {
        this.modeloAlta.clear();
        this.modeloBaja.clear();
        this.modeloCursadaMod.clear();
        this.modeloAsignaturaMod.clear();
        this.modeloCursadaConsulta.clear();
        this.modeloAlumnoConsulta.clear();
        this.modeloProfesorConsulta.clear();
        this.modeloHorariosConsulta.clear();

    }
    public void cerrar() {
        try{
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e) {
                    ventana.setVisible(true);
                }
            });
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        buttonGroupAlta = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAlta = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreAlta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAlta = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuscarAlta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1CAlta = new javax.swing.JRadioButton();
        jRadioButton2CAlta = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButtonAltasBajasAlumnosAlta = new javax.swing.JButton();
        jButtonAltasBajasProfesoresAlta = new javax.swing.JButton();
        jButtonAltasBajasHorariosAlta = new javax.swing.JButton();
        jButtonVolverAlta = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonCrearCursadaAlta = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerAlta = new javax.swing.JSpinner();
        jPanel32 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanelBaja = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreBaja = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarBaja = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListBaja = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButtonVolverBaja = new javax.swing.JButton();
        jButtonEliminarBaja = new javax.swing.JButton();
        jPanelModificaciones = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNombreMod = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCursadasMod = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNombreNuevoMod = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jButtonBuscarAsigMod = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListAsigNuevaMod = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jRadioButton1CMod = new javax.swing.JRadioButton();
        jRadioButton2CMod = new javax.swing.JRadioButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jButtonAltasBajasAlumnosMod = new javax.swing.JButton();
        jButtonAltasBajasProfesoresMod = new javax.swing.JButton();
        jButtonAltasBajasHorariosMod = new javax.swing.JButton();
        jButtonVolverMod = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButtonBuscarMod = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jButtonConfirmarMod = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerMod = new javax.swing.JSpinner();
        jPanelConsulta = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNombreConsulta = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jButtonBuscarConsulta = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCursadasConsulta = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jButtonCargarConsulta = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIdConsulta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldNombreConsultaa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCuatrimestreConsulta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldAñoConsulta = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAlumnosConsulta = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListProfesoresConsulta = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jButtonVolverConsulta = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListHorariosConsulta = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelAlta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Nombre de asignatura");
        jPanel4.add(jLabel2);
        jPanel4.add(jTextFieldNombreAlta);

        jScrollPane1.setViewportView(jListAlta);

        jLabel3.setText("Seleccione la Asignatura de la cursada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarAlta.setText("Buscar");
        jButtonBuscarAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarAltaActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBuscarAlta);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroupAlta.add(jRadioButton1CAlta);
        jRadioButton1CAlta.setText("1°Cuatrimestre");
        jPanel3.add(jRadioButton1CAlta);

        buttonGroupAlta.add(jRadioButton2CAlta);
        jRadioButton2CAlta.setText("2°Cuatrimestre");
        jPanel3.add(jRadioButton2CAlta);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Ingrese el cuatrimestre");
        jPanel6.add(jLabel1);

        jPanel8.setLayout(new java.awt.GridLayout(2, 2));

        jButtonAltasBajasAlumnosAlta.setText("Altas/Bajas de Alumnos");
        jPanel8.add(jButtonAltasBajasAlumnosAlta);

        jButtonAltasBajasProfesoresAlta.setText("Altas/Bajas de Profesores");
        jPanel8.add(jButtonAltasBajasProfesoresAlta);

        jButtonAltasBajasHorariosAlta.setText("Altas/Bajas Horarios");
        jPanel8.add(jButtonAltasBajasHorariosAlta);

        jButtonVolverAlta.setText("Volver");
        jButtonVolverAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonVolverAltaActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonVolverAlta);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCrearCursadaAlta.setText("Crear Cursada");
        jButtonCrearCursadaAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCrearCursadaAltaActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonCrearCursadaAlta);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setText("       20");
        jPanel7.add(jLabel4);
        jPanel7.add(jSpinnerAlta);

        jLabel23.setText("Ingrese el año");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23))
        );

        javax.swing.GroupLayout jPanelAltaLayout = new javax.swing.GroupLayout(jPanelAlta);
        jPanelAlta.setLayout(jPanelAltaLayout);
        jPanelAltaLayout.setHorizontalGroup(
            jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelAltaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAltaLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(27, 27, 27)))
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAltaLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelAltaLayout.setVerticalGroup(
            jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAltaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(531, Short.MAX_VALUE)))
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAltaLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(388, Short.MAX_VALUE)))
            .addGroup(jPanelAltaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAltaLayout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Alta", jPanelAlta);

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setText("Nombre de la Asignatura de la cursada");
        jPanel10.add(jLabel5);
        jPanel10.add(jTextFieldNombreBaja);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarBaja.setText("Buscar");
        jButtonBuscarBaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarBajaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarBaja);

        jScrollPane2.setViewportView(jListBaja);

        jLabel6.setText("Seleccione la cursada a dar de baja");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jButtonVolverBaja.setText("Volver");
        jButtonVolverBaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonVolverBajaActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonVolverBaja);

        jButtonEliminarBaja.setText("Eliminar");
        jButtonEliminarBaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEliminarBajaActionPerformed(evt);
            }
        });
        jPanel12.add(jButtonEliminarBaja);

        javax.swing.GroupLayout jPanelBajaLayout = new javax.swing.GroupLayout(jPanelBaja);
        jPanelBaja.setLayout(jPanelBajaLayout);
        jPanelBajaLayout.setHorizontalGroup(
            jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap(289, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanelBajaLayout.setVerticalGroup(
            jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(486, Short.MAX_VALUE)))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(361, Short.MAX_VALUE)))
            .addGroup(jPanelBajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBajaLayout.createSequentialGroup()
                    .addGap(238, 238, 238)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Baja", jPanelBaja);

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        jLabel7.setText("Nombre de la Asignatura de la cursada");
        jPanel13.add(jLabel7);
        jPanel13.add(jTextFieldNombreMod);

        jScrollPane3.setViewportView(jListCursadasMod);

        jLabel8.setText("Seleccione la cursada a modificar");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new java.awt.GridLayout(1, 2));

        jLabel9.setText("Nombre de la asignatura nueva");
        jPanel16.add(jLabel9);
        jPanel16.add(jTextFieldNombreNuevoMod);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarAsigMod.setText("Buscar");
        jButtonBuscarAsigMod.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarAsigModActionPerformed(evt);
            }
        });
        jPanel17.add(jButtonBuscarAsigMod);

        jScrollPane4.setViewportView(jListAsigNuevaMod);

        jLabel10.setText("Seleccione la Asignatura nueva que quiere asignar");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jRadioButton1CMod.setText("1°Cuatrimestre");
        jPanel19.add(jRadioButton1CMod);

        jRadioButton2CMod.setText("2°Cuatrimestre");
        jPanel19.add(jRadioButton2CMod);

        jPanel21.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setText("Modificar Cuatrimestre");
        jPanel21.add(jLabel12);

        jPanel22.setLayout(new java.awt.GridLayout(2, 2));

        jButtonAltasBajasAlumnosMod.setText("Altas/Bajas de Alumnos");
        jPanel22.add(jButtonAltasBajasAlumnosMod);

        jButtonAltasBajasProfesoresMod.setText("Altas/Bajas de Profesores");
        jPanel22.add(jButtonAltasBajasProfesoresMod);

        jButtonAltasBajasHorariosMod.setText("Altas/Bajas Horarios");
        jPanel22.add(jButtonAltasBajasHorariosMod);

        jButtonVolverMod.setText("Volver");
        jButtonVolverMod.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonVolverModActionPerformed(evt);
            }
        });
        jPanel22.add(jButtonVolverMod);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarMod.setText("Buscar");
        jButtonBuscarMod.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarModActionPerformed(evt);
            }
        });
        jPanel14.add(jButtonBuscarMod);

        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        jButtonConfirmarMod.setText("Confirmar cambios");
        jButtonConfirmarMod.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonConfirmarModActionPerformed(evt);
            }
        });
        jPanel24.add(jButtonConfirmarMod);

        jLabel24.setText("Ingrese el año");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel24))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24))
        );

        jPanel20.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setText("       20");
        jPanel20.add(jLabel11);
        jPanel20.add(jSpinnerMod);

        javax.swing.GroupLayout jPanelModificacionesLayout = new javax.swing.GroupLayout(jPanelModificaciones);
        jPanelModificaciones.setLayout(jPanelModificacionesLayout);
        jPanelModificacionesLayout.setHorizontalGroup(
            jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(407, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(415, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(459, 459, 459)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
        jPanelModificacionesLayout.setVerticalGroup(
            jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(192, 192, 192)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(225, 225, 225)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(324, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(258, 258, 258)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(381, 381, 381)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(349, 349, 349)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(0, 516, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(374, 374, 374)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
            .addGroup(jPanelModificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelModificacionesLayout.createSequentialGroup()
                    .addGap(385, 385, 385)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificaciones", jPanelModificaciones);

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(new java.awt.GridLayout(1, 2));

        jLabel13.setText("Nombre de la Asignatura de la cursada");
        jPanel23.add(jLabel13);
        jPanel23.add(jTextFieldNombreConsulta);

        jPanel25.setLayout(new java.awt.GridLayout(1, 0));

        jButtonBuscarConsulta.setText("Buscar");
        jButtonBuscarConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarConsultaActionPerformed(evt);
            }
        });
        jPanel25.add(jButtonBuscarConsulta);

        jScrollPane5.setViewportView(jListCursadasConsulta);

        jLabel14.setText("Seleccione la cursada a consultar");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel27.setLayout(new java.awt.GridLayout(1, 0));

        jButtonCargarConsulta.setText("Cargar");
        jButtonCargarConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCargarConsultaActionPerformed(evt);
            }
        });
        jPanel27.add(jButtonCargarConsulta);

        jPanel28.setLayout(new java.awt.GridLayout(4, 2));

        jLabel15.setText("ID de cursada");
        jPanel28.add(jLabel15);
        jPanel28.add(jTextFieldIdConsulta);

        jLabel16.setText("Nombre de Asignatura");
        jPanel28.add(jLabel16);

        jTextFieldNombreConsultaa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldNombreConsultaaActionPerformed(evt);
            }
        });
        jPanel28.add(jTextFieldNombreConsultaa);

        jLabel17.setText("Cuatrimeste");
        jPanel28.add(jLabel17);
        jPanel28.add(jTextFieldCuatrimestreConsulta);

        jLabel18.setText("Año");
        jPanel28.add(jLabel18);

        jTextFieldAñoConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldAñoConsultaActionPerformed(evt);
            }
        });
        jPanel28.add(jTextFieldAñoConsulta);

        jListAlumnosConsulta.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jListAlumnosConsulta);

        jLabel21.setText("Lista de Alumnos");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 210, Short.MAX_VALUE))
            .addComponent(jScrollPane6)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListProfesoresConsulta.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jListProfesoresConsulta);

        jLabel22.setText("Lista de Profesores");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 204, Short.MAX_VALUE))
            .addComponent(jScrollPane7)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel31.setLayout(new java.awt.GridLayout(1, 0));

        jButtonVolverConsulta.setText("Volver");
        jPanel31.add(jButtonVolverConsulta);

        jListHorariosConsulta.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jListHorariosConsulta);

        jLabel19.setText("Horarios");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 90, Short.MAX_VALUE))
            .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConsultaLayout.createSequentialGroup()
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 302, Short.MAX_VALUE))
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap(308, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap(483, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(535, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(513, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelConsultaLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                    .addContainerGap(392, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
            .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                    .addGap(0, 549, Short.MAX_VALUE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }//GEN-END:initComponents

    private void jButtonBuscarAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarAltaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Asignatura> asignaturas=this.facultad.buscarAsignaturaPorNombre(this.jTextFieldNombreAlta.getText().toUpperCase());
        Iterator it=asignaturas.iterator();

        while(it.hasNext())
        {
            Asignatura a=(Asignatura)it.next();
            modeloAlta.addElement(a);
        }
        this.jListAlta.setModel(modeloAlta);
    }//GEN-LAST:event_jButtonBuscarAltaActionPerformed

    private void jButtonBuscarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarBajaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Cursada> cursadas=this.facultad.buscarCursadaPorNombre(this.jTextFieldNombreBaja.getText().toUpperCase());
        Iterator it=cursadas.iterator();

        while(it.hasNext())
        {
            Cursada c=(Cursada)it.next();
            modeloBaja.addElement(c);
        }
        this.jListBaja.setModel(modeloBaja);
    }//GEN-LAST:event_jButtonBuscarBajaActionPerformed

    private void jButtonVolverBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverBajaActionPerformed
        // TODO add your handling code here:
        this.ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverBajaActionPerformed

    private void jButtonEliminarBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEliminarBajaActionPerformed
    {//GEN-HEADEREND:event_jButtonEliminarBajaActionPerformed
        // TODO add your handling code here:
        int n=this.jListBaja.getSelectedIndex();
        Cursada c=(Cursada) this.modeloBaja.getElementAt(n);
        this.facultad.bajaCursada(c);
        this.limpiarModelo();
        JOptionPane.showMessageDialog(null,"La cursada fue eliminada con exito","Gracias",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonEliminarBajaActionPerformed

    private void jButtonBuscarAsigModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarAsigModActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarAsigModActionPerformed
        // TODO add your handling code here:
        ArrayList<Asignatura> asignaturas=this.facultad.buscarAsignaturaPorNombre(this.jTextFieldNombreNuevoMod.getText().toUpperCase());
        Iterator it=asignaturas.iterator();

        while(it.hasNext())
        {
            Asignatura a=(Asignatura)it.next();
            this.modeloAsignaturaMod.addElement(a);
        }
        this.jListAsigNuevaMod.setModel(this.modeloAsignaturaMod);
    }//GEN-LAST:event_jButtonBuscarAsigModActionPerformed

    private void jButtonBuscarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarModActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarModActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Cursada> cursadas=this.facultad.buscarCursadaPorNombre(this.jTextFieldNombreMod.getText().toUpperCase());
        Iterator it=cursadas.iterator();

        while(it.hasNext())
        {
            Cursada c=(Cursada)it.next();
            this.modeloCursadaMod.addElement(c);
        }
        this.jListCursadasMod.setModel(modeloCursadaMod);
    }//GEN-LAST:event_jButtonBuscarModActionPerformed

    private void jButtonBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarConsultaActionPerformed
        // TODO add your handling code here:
        this.limpiarModelo();
        ArrayList<Cursada> cursadas=this.facultad.buscarCursadaPorNombre(this.jTextFieldNombreConsulta.getText().toUpperCase());
        Iterator it=cursadas.iterator();

        while(it.hasNext())
        {
            Cursada c=(Cursada)it.next();
            this.modeloCursadaConsulta.addElement(c);
        }
        this.jListCursadasConsulta.setModel(modeloCursadaConsulta);
    }//GEN-LAST:event_jButtonBuscarConsultaActionPerformed

    private void jTextFieldNombreConsultaaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNombreConsultaaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNombreConsultaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreConsultaaActionPerformed

    private void jTextFieldAñoConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldAñoConsultaActionPerformed
    {//GEN-HEADEREND:event_jTextFieldAñoConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoConsultaActionPerformed

    private void jButtonCrearCursadaAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCrearCursadaAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonCrearCursadaAltaActionPerformed
        // TODO add your handling code here:
        
        if(this.jRadioButton1CAlta.isSelected() || this.jRadioButton2CAlta.isSelected())
        {
            Integer i;
            Integer i2=new Integer(2016);
            i=(Integer)this.jSpinnerAlta.getValue();
            i+=2000;
            if(i>i2)
            {
                int n=this.jListAlta.getSelectedIndex();
                if(n!=-1){
                Asignatura a=(Asignatura) this.modeloAlta.getElementAt(n);
                String s;
                if(this.jRadioButton1CAlta.isSelected())
                {
                    s="01-";                            
                }else
                {
                    s="02-";
                }
                s+=i.toString();
                this.facultad.agregarCursada(a, s);
                JOptionPane.showMessageDialog(null, "La cursada fue creada con exito");
                this.limpiarModelo();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Seleccione una asignatura por favor","Error",JOptionPane.ERROR_MESSAGE);   
                }
             }
                else{
                    JOptionPane.showMessageDialog(null, "El año ingresado es incorrecto","Error",JOptionPane.ERROR_MESSAGE);
                }
        }else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un cuatrimestre por favor","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonCrearCursadaAltaActionPerformed

    private void jButtonVolverAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverAltaActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverAltaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.ventana.setVisible(true);
    }//GEN-LAST:event_jButtonVolverAltaActionPerformed

    private void jButtonConfirmarModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirmarModActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirmarModActionPerformed
        // TODO add your handling code here:
        if(this.jRadioButton1CMod.isSelected() || this.jRadioButton2CMod.isSelected())
        {
            Integer i;
            Integer i2=new Integer(2016);
            i=(Integer)this.jSpinnerMod.getValue();
            i+=2000;
            if(i>i2)
            {
                int x=this.jListCursadasMod.getSelectedIndex();
                int n=this.jListAsigNuevaMod.getSelectedIndex();
                if(n!=-1 && x!=-1){
                Asignatura a=(Asignatura) this.modeloAsignaturaMod.getElementAt(n);
                Cursada c=(Cursada) this.modeloCursadaMod.getElementAt(x);
                String s;
                if(this.jRadioButton1CMod.isSelected())
                {
                    s="01-";                            
                }else
                {
                    s="02-";
                }
                s+=i.toString();
                c.setAsignatura(a);
                c.setPeriodo(s);
                this.limpiarModelo();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Seleccione una asignatura y una cursada por favor","Error",JOptionPane.ERROR_MESSAGE);   
                }
             }
                else{
                    JOptionPane.showMessageDialog(null, "El año ingresado es incorrecto","Error",JOptionPane.ERROR_MESSAGE);
                }
        }else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un cuatrimestre por favor","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonConfirmarModActionPerformed

    private void jButtonVolverModActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonVolverModActionPerformed
    {//GEN-HEADEREND:event_jButtonVolverModActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.ventana.setVisible(true);
    }//GEN-LAST:event_jButtonVolverModActionPerformed

    private void jButtonCargarConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCargarConsultaActionPerformed
    {//GEN-HEADEREND:event_jButtonCargarConsultaActionPerformed
        // TODO add your handling code here:
        int n=this.jListCursadasConsulta.getSelectedIndex();
        if(n!=-1){
        Cursada c=(Cursada) this.modeloCursadaConsulta.getElementAt(n);
        this.jTextFieldCuatrimestreConsulta.setText(c.getPeriodo().substring(0, 2));
        this.jTextFieldAñoConsulta.setText(c.getPeriodo().substring(3, 7));
        this.jTextFieldIdConsulta.setText(c.getId());
        this.jTextFieldNombreConsultaa.setText(c.getAsignatura().getNombre());
        
        ArrayList<Fecha> horarios=c.getHorario();
        Iterator it=horarios.iterator();
        Fecha fecha;
        while( it.hasNext()){
            fecha =(Fecha) it.next();
            this.modeloHorariosConsulta.addElement(fecha);
        }
        this.jListHorariosConsulta.setModel(modeloHorariosConsulta);
        Hashtable<String,Alumno> alumnos=c.getAlumnos();
        Enumeration e = alumnos.elements();
        Alumno a;
        while( e.hasMoreElements() ){
            a=(Alumno) e.nextElement();
            this.modeloAlumnoConsulta.addElement(a);
        }
        this.jListAlumnosConsulta.setModel(modeloAlumnoConsulta);
        Hashtable<String,Profesor> profesores=c.getProfesores();
        Enumeration e2 = profesores.elements();
        Profesor p;
        while( e2.hasMoreElements() ){
            p=(Profesor) e2.nextElement();
            this.modeloProfesorConsulta.addElement(p);
        }
        this.jListProfesoresConsulta.setModel(modeloProfesorConsulta);        
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una cursada","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCargarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaCursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaCursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaCursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaCursada.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    //new VentanaCursada().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAlta;
    private javax.swing.JButton jButtonAltasBajasAlumnosAlta;
    private javax.swing.JButton jButtonAltasBajasAlumnosMod;
    private javax.swing.JButton jButtonAltasBajasHorariosAlta;
    private javax.swing.JButton jButtonAltasBajasHorariosMod;
    private javax.swing.JButton jButtonAltasBajasProfesoresAlta;
    private javax.swing.JButton jButtonAltasBajasProfesoresMod;
    private javax.swing.JButton jButtonBuscarAlta;
    private javax.swing.JButton jButtonBuscarAsigMod;
    private javax.swing.JButton jButtonBuscarBaja;
    private javax.swing.JButton jButtonBuscarConsulta;
    private javax.swing.JButton jButtonBuscarMod;
    private javax.swing.JButton jButtonCargarConsulta;
    private javax.swing.JButton jButtonConfirmarMod;
    private javax.swing.JButton jButtonCrearCursadaAlta;
    private javax.swing.JButton jButtonEliminarBaja;
    private javax.swing.JButton jButtonVolverAlta;
    private javax.swing.JButton jButtonVolverBaja;
    private javax.swing.JButton jButtonVolverConsulta;
    private javax.swing.JButton jButtonVolverMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListAlta;
    private javax.swing.JList<String> jListAlumnosConsulta;
    private javax.swing.JList<String> jListAsigNuevaMod;
    private javax.swing.JList<String> jListBaja;
    private javax.swing.JList<String> jListCursadasConsulta;
    private javax.swing.JList<String> jListCursadasMod;
    private javax.swing.JList<String> jListHorariosConsulta;
    private javax.swing.JList<String> jListProfesoresConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAlta;
    private javax.swing.JPanel jPanelBaja;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelModificaciones;
    private javax.swing.JRadioButton jRadioButton1CAlta;
    private javax.swing.JRadioButton jRadioButton1CMod;
    private javax.swing.JRadioButton jRadioButton2CAlta;
    private javax.swing.JRadioButton jRadioButton2CMod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinnerAlta;
    private javax.swing.JSpinner jSpinnerMod;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAñoConsulta;
    private javax.swing.JTextField jTextFieldCuatrimestreConsulta;
    private javax.swing.JTextField jTextFieldIdConsulta;
    private javax.swing.JTextField jTextFieldNombreAlta;
    private javax.swing.JTextField jTextFieldNombreBaja;
    private javax.swing.JTextField jTextFieldNombreConsulta;
    private javax.swing.JTextField jTextFieldNombreConsultaa;
    private javax.swing.JTextField jTextFieldNombreMod;
    private javax.swing.JTextField jTextFieldNombreNuevoMod;
    // End of variables declaration//GEN-END:variables

}
